
all:
  data_dir: 'data/'
  log_dir: 'logs/analysis/'
  output_dir_results: 'results/analysis/Neutro_Epi_extImm_pooled_A_EM_N/'
  output_dir_plots: 'plots/analysis/Neutro_Epi_extImm_pooled_A_EM_N/'

exclude_v17: False

phenotyping_level: 'Neutro_Epi_extImm_pooled_A_EM_N'

patch_size: 5000
overlap: 50