#!/usr/bin/python3
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# kontextual_ripleys.py
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
#   Two parallel cross-type Ripley's L statistics matching R Statial output:
#
#   L_original   (= R "original"):
#     Standard homogeneous cross-type L using the global observation window.
#     K(r) = area/(n_i*n_j) * sum_i[ edge_i(r) * count_j(r|i) ]
#     Null: global label permutation across all cells, same global window.
#
#   L_kontextual (= R "kontextual", Canete et al. 2022):
#     Inhomogeneous L where intensity is estimated from local parent-cell
#     density rather than a global area-based constant.
#     K(r) = (n_pool/n_j)*pi*r^2 * sum_pairs[edge_i*n_p_i/n_p_j]
#                                 / sum_sources[n_p_i]
#     where n_p_x(r) = count of parent cells within r of cell x.
#     Null: within-parent label permutation, same global window + cached
#           parent counts (parent cell positions are permutation-invariant).
#
#   Both statistics share the same permutation draws and cached parent counts,
#   so the cost overhead of the second statistic is modest.
#
#   Global window (convex hull of all cells) is used for edge correction in
#   both statistics, matching R Statial's makeWindow("convex") behaviour.
#   No per-pool sub-window is constructed.
#
#   0  Import libraries and parse arguments
#   1  Read data
#   2  Define analysis functions
#   3  Global window + per-pool cache (parent counts)
#   4  Main analysis loop
#   5  Build summary table and save results
#
#
# Usage:
#   python3 /net/beegfs/groups/tgac/dmartinovicova_new/DIRECT/scripts/analysis_and_plotting/kontextual_ripleys.py \
#     -i /net/beegfs/groups/tgac/dmartinovicova_new/DIRECT/data/adata_per_sample/Neutro_Epi_extImm_pooled_A_EM_N/T23_004535_110005_1.h5ad \
#     --parent_comb  /net/beegfs/groups/tgac/dmartinovicova_new/DIRECT/data/analyzed/Neutro_Epi_extImm_pooled_A_EM_N_parent_combinations.csv \
#     --phen_level   Neutro_Epi_extImm_pooled_A_EM_N \
#     -o  /net/beegfs/groups/tgac/dmartinovicova_new/DIRECT/results/analysis/Neutro_Epi_extImm_pooled_A_EM_N/spatial/per_patch/5000um_50um/T23_004535_110005_1_window_0/kontextual \
#     [--n_sim 100] [--seed 42] [--min_cells 3] \
#     [--coi B_cell Macrophage Macrophage_alveolar NK_cell Stromal T_cell_CD4 T_cell_CD8_functional T_cell_CD8_terminally_exhausted T_cell_regulatory Tumor_cells]
# #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#==============================================================================
# 0  Import libraries and parse arguments
#==============================================================================
import numpy as np
import scanpy as sc
import pandas as pd
from scipy.spatial import ConvexHull, cKDTree
from numpy.random import default_rng
from shapely.geometry import Polygon
import argparse
import os
import pickle
import matplotlib.pyplot as plt
from tqdm import tqdm


def parse_args():
    parser = argparse.ArgumentParser(
        prog='python3 kontextual_ripleys.py',
        formatter_class=argparse.RawTextHelpFormatter,
        description='Context-aware cross-type Ripley\'s L (kontextual).')
    parser.add_argument('-i', dest='input', type=str, required=True,
                        help='Path to input .h5ad adata file')
    parser.add_argument('--parent_comb', dest='parent_comb', type=str, required=True,
                        help='Path to parent combinations TSV '
                             '(columns: from, to, parent, parent_name)')
    parser.add_argument('--phen_level', dest='phen_level', type=str, required=True,
                        help='Key for cell type annotation in adata.obs')
    parser.add_argument('-o', '--output_results', dest='output_dir_results', type=str,
                        required=True, help='Output directory for results (pickle + TSV)')
    parser.add_argument('--output_plots', dest='output_dir_plots', type=str,
                        default=None,
                        help='(Unused — heatmaps are generated by plot_kontextual_curves.py)')
    parser.add_argument('--n_sim', type=int, default=500,
                        help='Number of permutation simulations (default: 500)')
    parser.add_argument('--seed', type=int, default=42,
                        help='Random seed for reproducibility (default: 42)')
    parser.add_argument('--min_cells', type=int, default=3,
                        help='Minimum cells per type required to compute L (default: 3)')
    parser.add_argument('--coi', dest='coi', nargs='+',
                        default=[
                            'B_cell', 'Macrophage', 'Macrophage_alveolar',
                            'NK_cell', 'Stromal', 'T_cell_CD4',
                            'T_cell_CD8_functional', 'T_cell_CD8_terminally_exhausted',
                            'T_cell_regulatory', 'Tumor_cells',
                        ],
                        help='Cell types of interest (space-separated). Only pairs where '
                             'both from and to are in this list are analysed.')
    return parser.parse_args()


args = parse_args()

#==============================================================================
# 1  Read data
#==============================================================================
os.makedirs(args.output_dir_results, exist_ok=True)
if args.output_dir_plots:
    os.makedirs(args.output_dir_plots, exist_ok=True)

print(f"Reading adata: {args.input}")
adata = sc.read_h5ad(args.input)
cluster_key = args.phen_level

coordinates = np.asarray(adata.obsm["spatial"], dtype=float)
labels      = np.asarray(adata.obs[cluster_key])
present_types = set(np.unique(labels))

print(f"  {adata.n_obs} cells, {len(present_types)} cell types")
print(f"  Cell type counts:\n{adata.obs[cluster_key].value_counts().to_string()}\n")

# Radii to evaluate (µm)
RADII = np.array([25, 50, 75, 100, 150, 200], dtype=float)
N_R   = len(RADII)

print(f"Reading parent combinations: {args.parent_comb}")
parent_comb = pd.read_csv(args.parent_comb, sep='\t')
parent_comb['parent_list'] = parent_comb['parent'].apply(lambda x: x.split(','))

# Keep only rows where both from and to are present in this adata
n_total = len(parent_comb)
parent_comb = parent_comb[
    parent_comb['from'].isin(present_types) & parent_comb['to'].isin(present_types)
].reset_index(drop=True)
print(f"  {n_total} pairs in CSV → {len(parent_comb)} with both types present")

# Restrict to cell types of interest
coi_set = set(args.coi)
n_before = len(parent_comb)
parent_comb = parent_comb[
    parent_comb['from'].isin(coi_set) & parent_comb['to'].isin(coi_set)
].reset_index(drop=True)
print(f"  COI filter ({len(coi_set)} types) → {len(parent_comb)} pairs retained "
      f"(dropped {n_before - len(parent_comb)})")
print()

rng = default_rng(args.seed)

#==============================================================================
# 2  Define analysis functions
#==============================================================================

def build_convex_hull_polygon(coords):
    """Return a shapely Polygon for the convex hull of coords (n, 2)."""
    hull = ConvexHull(coords)
    return Polygon(coords[hull.vertices])


def min_dist_to_hull_boundary(coords, hull_vertices):
    """
    Vectorised minimum distance from each point to a convex polygon boundary.

    Parameters
    ----------
    coords        : (n_pts, 2) float array
    hull_vertices : (n_verts, 2) float array — ordered convex hull vertices

    Returns
    -------
    dists : (n_pts,) minimum distance from each point to the boundary
    """
    verts = np.asarray(hull_vertices, dtype=float)
    p0 = verts
    p1 = np.roll(verts, -1, axis=0)
    edge_vec    = p1 - p0
    edge_len_sq = np.sum(edge_vec ** 2, axis=1) + 1e-12

    pts = coords[:, np.newaxis, :]
    P0  = p0[np.newaxis, :, :]
    EV  = edge_vec[np.newaxis, :, :]

    t = np.sum((pts - P0) * EV, axis=2) / edge_len_sq
    t = np.clip(t, 0.0, 1.0)

    closest   = P0 + t[:, :, np.newaxis] * EV
    seg_dists = np.linalg.norm(pts - closest, axis=2)

    return seg_dists.min(axis=1)


def compute_edge_weights(coords, hull_vertices, radii, max_weight=3.0):
    """
    Isotropic edge correction weights (Ripley 1988).

    weight_i(r) = 1                       if dist_to_boundary(i) >= r
    weight_i(r) = min(r / dist_i, max_w)  otherwise

    Returns
    -------
    weights : (n_cells, n_radii)
    """
    dists   = min_dist_to_hull_boundary(coords, hull_vertices)
    weights = np.ones((len(coords), len(radii)), dtype=float)
    for k, r in enumerate(radii):
        near = dists < r
        if np.any(near):
            weights[near, k] = np.minimum(
                r / np.maximum(dists[near], 1e-6), max_weight
            )
    return weights


def precompute_parent_counts(query_coords, parent_coords, radii):
    """
    For each query cell, count parent cells within each radius.

    Self-pairs are included (a pool cell counts itself), matching R Statial's
    closepairs(..., distinct=FALSE) behaviour.

    Returns
    -------
    counts : (n_query, n_radii)  float32 array
    """
    tree   = cKDTree(parent_coords)
    nbs    = tree.query_ball_point(query_coords, radii[-1])
    counts = np.zeros((len(query_coords), len(radii)), dtype=np.float32)
    for i, nb_list in enumerate(nbs):
        if not nb_list:
            continue
        d = np.linalg.norm(parent_coords[np.array(nb_list)] - query_coords[i], axis=1)
        counts[i] = np.searchsorted(np.sort(d), radii, side='right')
    return counts


def cross_L_original(coords_i, coords_j, radii, weights_i, global_area):
    """
    Standard homogeneous cross-type Ripley's L  (R Statial 'original').

    Matches R's .Lfunction():
        K(r) = area / (n_i * n_j) * sum_i[ edge_i(r) * count_j(r|i) ]
        L(r) = sqrt(K / pi)   [un-centered; plotting subtracts r]

    Parameters
    ----------
    coords_i    : (n_i, 2)    source cell coordinates
    coords_j    : (n_j, 2)    target cell coordinates
    radii       : (n_r,)      evaluation radii
    weights_i   : (n_i, n_r)  pre-computed edge correction weights (global hull)
    global_area : float       area of the global convex hull window

    Returns
    -------
    L : (n_r,) un-centered Ripley's L
    """
    n_i, n_j = len(coords_i), len(coords_j)
    if n_i == 0 or n_j == 0:
        return np.full(len(radii), np.nan)

    lambda_j = n_j / global_area
    tree     = cKDTree(coords_j)
    nbs      = tree.query_ball_point(coords_i, radii[-1])

    weighted_sum = np.zeros(len(radii))
    for i, nb_list in enumerate(nbs):
        if not nb_list:
            continue
        d      = np.sort(np.linalg.norm(coords_j[np.array(nb_list)] - coords_i[i], axis=1))
        counts = np.searchsorted(d, radii, side='right')          # (n_r,)
        weighted_sum += counts * weights_i[i]                     # edge-weighted

    K = weighted_sum / lambda_j / n_i                             # (n_r,)
    return np.sqrt(np.maximum(K, 0.0) / np.pi)


def cross_L_kontextual(coords_i, coords_j,
                        n_parent_at_source, n_parent_at_target,
                        n_pool, n_j, weights_i, radii):
    """
    Inhomogeneous kontextual cross-type Ripley's L  (R Statial '.Kontext()').

    Uses local parent-cell density as the intensity function for both source
    and target cells, following Canete et al. 2022.

    Formula (per radius r):
        n_p_i(r) = count(parent cells within r of source i)
        n_p_j(r) = count(parent cells within r of target j)

        numerator(r)   = sum_{pairs (i,j) within r}
                            [ edge_i(r) * n_p_i * n_pool / (n_p_j * n_j) ]
        denominator(r) = sum_{source i} n_p_i(r)

        K(r) = pi * r^2 * numerator(r) / denominator(r)
        L(r) = sqrt(K / pi)   [un-centered]

    For uniform parent density this reduces to standard K / L.
    Pairs where n_p_j = 0 are skipped (undefined local density at target).
    Source cells with n_p_i = 0 contribute 0 to both numerator and denominator.

    Parameters
    ----------
    coords_i            : (n_i, 2)    source cell coordinates
    coords_j            : (n_j, 2)    target cell coordinates
    n_parent_at_source  : (n_i, n_r)  parent counts at source positions
    n_parent_at_target  : (n_j, n_r)  parent counts at target positions
    n_pool              : int         total number of parent (pool) cells
    n_j                 : int         total number of target cells
    weights_i           : (n_i, n_r)  edge correction weights (global hull)
    radii               : (n_r,)      evaluation radii

    Returns
    -------
    L : (n_r,) un-centered kontextual Ripley's L
    """
    if len(coords_i) == 0 or len(coords_j) == 0:
        return np.full(len(radii), np.nan)

    N_R  = len(radii)
    tree = cKDTree(coords_j)
    nbs  = tree.query_ball_point(coords_i, radii[-1])

    numerator   = np.zeros(N_R)
    denominator = np.zeros(N_R)

    for i, nb_list in enumerate(nbs):
        n_pi = n_parent_at_source[i]          # (N_R,)
        denominator += n_pi

        if not nb_list:
            continue

        nb_arr   = np.array(nb_list)
        d        = np.linalg.norm(coords_j[nb_arr] - coords_i[i], axis=1)
        sort_idx = np.argsort(d)
        d_sorted = d[sort_idx]
        nb_sorted = nb_arr[sort_idx]

        # Pre-fetch parent counts at all target neighbors: (n_nb, N_R)
        n_pj_all = n_parent_at_target[nb_sorted]

        for k, r in enumerate(radii):
            n_pi_k = n_pi[k]
            if n_pi_k == 0:
                continue

            n_in_r = int(np.searchsorted(d_sorted, r, side='right'))
            if n_in_r == 0:
                continue

            n_pj_k = n_pj_all[:n_in_r, k]
            valid   = n_pj_k > 0
            if not valid.any():
                continue

            # weight(i,j) = edge_i * n_p_i * n_pool / (n_p_j * n_j)
            numerator[k] += (weights_i[i, k] * n_pi_k
                             * np.sum(1.0 / n_pj_k[valid])
                             * n_pool / n_j)

    K = np.zeros(N_R)
    pos = (denominator > 0) & (numerator > 0)
    K[pos] = np.pi * radii[pos]**2 * numerator[pos] / denominator[pos]
    return np.sqrt(np.maximum(K, 0.0) / np.pi)


def _integral_stats(observed, sim_matrix, radii):
    """
    Compute signed integral and z-score statistics from observed L and sims.

    Parameters
    ----------
    observed   : (N_R,)
    sim_matrix : (n_valid, N_R)
    radii      : (N_R,)

    Returns
    -------
    dict with integral_signed, integral_abs, z_integral, p_integral,
    pvalues (per-radius), sim_mean, sim_std
    """
    sim_mean = np.nanmean(sim_matrix, axis=0)
    sim_std  = np.nanstd(sim_matrix,  axis=0)

    diff             = observed - sim_mean
    integral_signed  = float(np.trapezoid(diff,           radii))
    integral_abs     = float(np.trapezoid(np.abs(diff),   radii))

    obs_int_raw  = float(np.trapezoid(observed,  radii))
    sim_integrals = np.trapezoid(sim_matrix, radii, axis=1)

    int_std = sim_integrals.std()
    if int_std > 0:
        z_integral  = float((obs_int_raw - sim_integrals.mean()) / int_std)
        p_upper     = (np.sum(sim_integrals >= obs_int_raw) + 1) / (len(sim_integrals) + 1)
        p_integral  = float(np.minimum(p_upper, 1.0 - p_upper))
    else:
        z_integral = np.nan
        p_integral = np.nan

    n_valid = sim_matrix.shape[0]
    p_upper_per_r = (np.sum(sim_matrix >= observed[np.newaxis, :], axis=0) + 1) / (n_valid + 1)
    pvalues       = np.minimum(p_upper_per_r, 1.0 - p_upper_per_r)

    return dict(
        sim_mean        = sim_mean,
        sim_std         = sim_std,
        integral_signed = integral_signed,
        integral_abs    = integral_abs,
        z_integral      = z_integral,
        p_integral      = p_integral,
        pvalues         = pvalues,
    )


def empty_result(type_i, type_j, parent_name, reason):
    """NaN-filled result for skipped or failed pairs."""
    nan_r    = np.full(N_R, np.nan)
    empty_s  = np.empty((0, N_R))
    return {
        "type_i":                      type_i,
        "type_j":                      type_j,
        "parent_name":                 parent_name,
        "perm_pool_types":             [],
        "r":                           RADII.copy(),
        # original (homogeneous, global window)
        "L_original":                  nan_r.copy(),
        "L_original_sim_mean":         nan_r.copy(),
        "L_original_sim_std":          nan_r.copy(),
        "L_original_simulations":      empty_s.copy(),
        "pvalues_original":            nan_r.copy(),
        "integral_original":           np.nan,
        "integral_original_abs":       np.nan,
        "z_original":                  np.nan,
        "p_original":                  np.nan,
        # kontextual (inhomogeneous parent density, global window)
        "L_kontextual":                nan_r.copy(),
        "L_kontextual_sim_mean":       nan_r.copy(),
        "L_kontextual_sim_std":        nan_r.copy(),
        "L_kontextual_simulations":    empty_s.copy(),
        "pvalues_kontextual":          nan_r.copy(),
        "integral_kontextual":         np.nan,
        "integral_kontextual_abs":     np.nan,
        "z_kontextual":                np.nan,
        "p_kontextual":                np.nan,
        # counts / diagnostics
        "n_source_cells":              np.nan,
        "n_target_cells":              np.nan,
        "n_valid_simulations":         0,
        "n_failed_simulations":        0,
        "reason":                      reason,
    }


#==============================================================================
# 3  Global observation window  +  per-pool parent-count cache
#==============================================================================

# --- Global window (used for edge correction in ALL L computations) ----------
print("Building global observation window...")
_g_poly         = build_convex_hull_polygon(coordinates)
_g_hull_verts   = np.array(_g_poly.exterior.coords)[:-1]
global_area     = _g_poly.area
global_weights  = compute_edge_weights(coordinates, _g_hull_verts, RADII)
print(f"  Global area = {global_area:.0f} µm²  ({len(coordinates)} cells)\n")

# --- Per-pool cache -----------------------------------------------------------
# Key  : frozenset of pool cell-type strings
# Value: dict with coords, labels, indices, n_parent_at_pool, pool_global_weights
_pool_cache = {}


def get_pool(perm_types_iter):
    """
    Return cached pool data for the given set of cell types.
    Computes parent-count matrix on first access.
    Returns None if the pool has fewer than 4 cells.

    Stored fields
    -------------
    coords              : (n_pool, 2)
    labels              : (n_pool,)
    indices             : (n_pool,)   global cell indices
    n_parent_at_pool    : (n_pool, N_R) count of parent cells within each
                          radius of each pool cell (positions invariant
                          across label permutations → computed once)
    pool_global_weights : (n_pool, N_R) global edge-correction weights
    """
    key = frozenset(perm_types_iter)
    if key in _pool_cache:
        return _pool_cache[key]

    mask        = np.isin(labels, list(key))
    pool_idx    = np.where(mask)[0]
    pool_coords = coordinates[mask]
    pool_labels = labels[mask]

    if len(pool_coords) < 4:
        print(f"  [WARN] Pool {sorted(key)} has only {len(pool_coords)} cells — skipping.")
        _pool_cache[key] = None
        return None

    # Precompute parent counts for every pool cell at each radius.
    # This is computed once and reused for observed + all null simulations.
    n_parent_at_pool = precompute_parent_counts(pool_coords, pool_coords, RADII)

    pool = {
        "types":               key,
        "coords":              pool_coords,
        "labels":              pool_labels,
        "indices":             pool_idx,
        "n_parent_at_pool":    n_parent_at_pool,
        "pool_global_weights": global_weights[pool_idx],   # (n_pool, N_R)
    }
    _pool_cache[key] = pool
    print(f"  [POOL] {len(key)} types, {len(pool_coords)} cells  "
          f"({sorted(key)[:3]}{'...' if len(key) > 3 else ''})")
    return pool


#==============================================================================
# 4  Main analysis loop
#==============================================================================
results = {}

print(f"Running kontextual Ripley's L for {len(parent_comb)} pairs "
      f"(n_sim={args.n_sim}, seed={args.seed})\n")

for _, row in tqdm(parent_comb.iterrows(), total=len(parent_comb), desc="Pairs"):
    type_i      = row['from']
    type_j      = row['to']
    parent_name = row['parent_name']
    parent_list = row['parent_list']

    # Permutation pool = parent types ∩ present only.
    # type_j is NOT added: if it falls outside the parent compartment its
    # positions are fixed as the target across observed + all simulations.
    perm_types = set(parent_list) & present_types

    pool = get_pool(perm_types)
    if pool is None:
        results[(type_i, type_j)] = empty_result(
            type_i, type_j, parent_name, 'pool_too_small')
        continue

    perm_labels         = pool['labels']
    perm_coords         = pool['coords']
    n_parent_at_pool    = pool['n_parent_at_pool']   # (n_pool, N_R)
    pool_gw             = pool['pool_global_weights'] # (n_pool, N_R)
    n_pool              = len(perm_coords)

    mask_i = perm_labels == type_i
    n_i    = int(np.sum(mask_i))

    # -----------------------------------------------------------------------
    # Target cells: fixed if type_j is outside the parent pool
    # -----------------------------------------------------------------------
    type_j_in_pool = type_j in perm_types
    if type_j_in_pool:
        # All type_j cells are within the pool; their labels are permuted.
        mask_j         = perm_labels == type_j
        n_j            = int(np.sum(mask_j))
        coords_j_fixed = None        # resolved from pool per permutation
        n_par_tgt_fixed = None
    else:
        # type_j is outside the parent compartment — positions are invariant.
        mask_j_global   = labels == type_j
        coords_j_fixed  = coordinates[mask_j_global]
        n_j             = int(np.sum(mask_j_global))
        # Parent counts at fixed target positions (precomputed once; pool
        # positions never change, only labels within pool are shuffled).
        n_par_tgt_fixed = precompute_parent_counts(
                              coords_j_fixed, perm_coords, RADII)

    if n_i < args.min_cells:
        res = empty_result(type_i, type_j, parent_name, 'insufficient_source_cells')
        res['n_source_cells'] = n_i
        res['n_target_cells'] = n_j
        results[(type_i, type_j)] = res
        continue
    if n_j < args.min_cells:
        res = empty_result(type_i, type_j, parent_name, 'insufficient_target_cells')
        res['n_source_cells'] = n_i
        res['n_target_cells'] = n_j
        results[(type_i, type_j)] = res
        continue

    # -----------------------------------------------------------------------
    # Observed L_original and L_kontextual
    # -----------------------------------------------------------------------
    coords_i        = perm_coords[mask_i]
    weights_i       = pool_gw[mask_i]
    n_parent_at_src = n_parent_at_pool[mask_i]   # (n_i, N_R)

    if type_j_in_pool:
        coords_j      = perm_coords[mask_j]
        n_par_tgt_obs = n_parent_at_pool[mask_j]  # (n_j, N_R)
    else:
        coords_j      = coords_j_fixed
        n_par_tgt_obs = n_par_tgt_fixed

    L_obs_orig = cross_L_original(
        coords_i, coords_j, RADII, weights_i, global_area)

    L_obs_kont = cross_L_kontextual(
        coords_i, coords_j,
        n_parent_at_src, n_par_tgt_obs,
        n_pool, n_j, weights_i, RADII)

    # -----------------------------------------------------------------------
    # Permutation nulls (one draw per statistic, per simulation):
    #
    # L_original null — global label permutation:
    #   All cell labels are reshuffled across the entire tissue.  Tests
    #   whether type_i clusters near type_j more than expected under
    #   complete spatial randomness of cell identity.  This matches
    #   R Statial's relabelCells behaviour and avoids the degenerate
    #   trivial null that arises when the parent pool contains only type_i.
    #
    # L_kontextual null — parent-pool label permutation:
    #   Labels are shuffled only within the parent compartment.  Tests
    #   whether the observed enrichment exceeds what is expected if type_i
    #   were randomly distributed within its parent population.
    #   - type_j INSIDE pool : target coords + parent counts change each draw.
    #   - type_j OUTSIDE pool: target coords + parent counts are invariant;
    #     only source assignment changes.
    #   Pool cell positions never move → n_parent_at_pool is reused as-is.
    # -----------------------------------------------------------------------
    sims_orig = []
    sims_kont = []
    n_failed  = 0

    for _ in range(args.n_sim):
        # --- L_original null: permute ALL labels globally ----------------
        # Counts are preserved across permutation so min-cells never fails.
        perm_global  = rng.permutation(labels)
        mask_i_g     = perm_global == type_i
        mask_j_g     = perm_global == type_j
        ci_g         = coordinates[mask_i_g]
        wi_g         = global_weights[mask_i_g]
        cj_g         = coordinates[mask_j_g]

        Lo = cross_L_original(ci_g, cj_g, RADII, wi_g, global_area)
        sims_orig.append(Lo)

        # --- L_kontextual null: permute labels within parent pool only ---
        perm_l   = rng.permutation(perm_labels)
        mask_i_p = perm_l == type_i
        ci = perm_coords[mask_i_p]
        wi = pool_gw[mask_i_p]

        if type_j_in_pool:
            mask_j_p    = perm_l == type_j
            nj_p        = int(np.sum(mask_j_p))
            cj          = perm_coords[mask_j_p]
            n_par_tgt_p = n_parent_at_pool[mask_j_p]
        else:
            cj          = coords_j_fixed
            nj_p        = n_j
            n_par_tgt_p = n_par_tgt_fixed

        Lk = cross_L_kontextual(
                 ci, cj,
                 n_parent_at_pool[mask_i_p],
                 n_par_tgt_p,
                 n_pool, nj_p, wi, RADII)
        sims_kont.append(Lk)

    n_valid = len(sims_orig)

    if n_valid == 0:
        res = empty_result(type_i, type_j, parent_name, 'no_valid_simulations')
        res['n_source_cells'] = n_i
        res['n_target_cells'] = n_j
        results[(type_i, type_j)] = res
        continue

    sims_orig = np.array(sims_orig)   # (n_valid, N_R)
    sims_kont = np.array(sims_kont)   # (n_valid, N_R)

    # -----------------------------------------------------------------------
    # Statistics for original and kontextual
    # -----------------------------------------------------------------------
    stats_orig = _integral_stats(L_obs_orig, sims_orig, RADII)
    stats_kont = _integral_stats(L_obs_kont, sims_kont, RADII)

    results[(type_i, type_j)] = {
        "type_i":      type_i,
        "type_j":      type_j,
        "parent_name": parent_name,
        "perm_pool_types": sorted(perm_types),
        "r":           RADII.copy(),
        # ---- original (homogeneous, global window) = R "original" ----
        "L_original":              L_obs_orig,
        "L_original_sim_mean":     stats_orig['sim_mean'],
        "L_original_sim_std":      stats_orig['sim_std'],
        "L_original_simulations":  sims_orig,
        "pvalues_original":        stats_orig['pvalues'],
        "integral_original":       stats_orig['integral_signed'],
        "integral_original_abs":   stats_orig['integral_abs'],
        "z_original":              stats_orig['z_integral'],
        "p_original":              stats_orig['p_integral'],
        # ---- kontextual (inhomogeneous parent, global window) = R "kontextual" ----
        "L_kontextual":             L_obs_kont,
        "L_kontextual_sim_mean":    stats_kont['sim_mean'],
        "L_kontextual_sim_std":     stats_kont['sim_std'],
        "L_kontextual_simulations": sims_kont,
        "pvalues_kontextual":       stats_kont['pvalues'],
        "integral_kontextual":      stats_kont['integral_signed'],
        "integral_kontextual_abs":  stats_kont['integral_abs'],
        "z_kontextual":             stats_kont['z_integral'],
        "p_kontextual":             stats_kont['p_integral'],
        # ---- counts / diagnostics ----
        "n_source_cells":       n_i,
        "n_target_cells":       n_j,
        "n_valid_simulations":  n_valid,
        "n_failed_simulations": n_failed,
        "reason":               None,
    }

print(f"\nFinished cross-type pairs: "
      f"{sum(1 for v in results.values() if v['reason'] is None)} computed, "
      f"{sum(1 for v in results.values() if v['reason'] is not None)} skipped.")

#==============================================================================
# 4b  Diagonal: same-type self-clustering  (L_original + L_kontextual)
#==============================================================================
# L_original null : global label permutation (same as cross-type).
# L_kontextual    : uses the same parent compartment as defined for ct-as-source
#                   in parent_comb.  If the pool contains only ct (e.g. Tumor_cells
#                   whose parent = self), the kontextual null is degenerate and is
#                   stored as NaN — the original curve still carries full information.

print(f"\nComputing diagonal (self-clustering) for {len(args.coi)} COI types...")

# Build lookup: ct → (parent_list, parent_name) from the first matching row
_ct_parent = {}
for ct in args.coi:
    rows = parent_comb[parent_comb['from'] == ct]
    if len(rows) > 0:
        _ct_parent[ct] = (rows.iloc[0]['parent_list'], rows.iloc[0]['parent_name'])
    else:
        _ct_parent[ct] = ([ct], 'self')

for ct in args.coi:
    if ct not in present_types:
        print(f"  [{ct}] not present — skipping")
        continue

    mask_ct  = labels == ct
    n_ct     = int(np.sum(mask_ct))

    if n_ct < args.min_cells:
        res = empty_result(ct, ct, 'self', 'insufficient_source_cells')
        res['n_source_cells'] = n_ct
        res['n_target_cells'] = n_ct
        results[(ct, ct)] = res
        print(f"  [{ct}] only {n_ct} cells — skipped")
        continue

    coords_ct  = coordinates[mask_ct]
    weights_ct = global_weights[mask_ct]

    # ------------------------------------------------------------------
    # Observed L_original (self-clustering, global window)
    # ------------------------------------------------------------------
    L_obs_orig = cross_L_original(
        coords_ct, coords_ct, RADII, weights_ct, global_area)

    # ------------------------------------------------------------------
    # Observed L_kontextual (self-clustering, parent-density weighted)
    # ------------------------------------------------------------------
    parent_list_ct, parent_name_ct = _ct_parent[ct]
    perm_types_ct = set(parent_list_ct) & present_types
    pool_ct       = get_pool(perm_types_ct)

    nan_r = np.full(N_R, np.nan)

    if pool_ct is not None:
        perm_labels_ct   = pool_ct['labels']
        perm_coords_ct   = pool_ct['coords']
        n_par_at_pool_ct = pool_ct['n_parent_at_pool']
        pool_gw_ct       = pool_ct['pool_global_weights']
        n_pool_ct        = len(perm_coords_ct)

        mask_src = perm_labels_ct == ct
        n_src    = int(np.sum(mask_src))

        if n_src >= args.min_cells:
            ci_ct        = perm_coords_ct[mask_src]
            wi_ct        = pool_gw_ct[mask_src]
            n_par_src_ct = n_par_at_pool_ct[mask_src]
            # source == target for self-pair
            L_obs_kont = cross_L_kontextual(
                ci_ct, ci_ct,
                n_par_src_ct, n_par_src_ct,
                n_pool_ct, n_src, wi_ct, RADII)
        else:
            L_obs_kont = nan_r.copy()
            pool_ct    = None          # flag: skip kontextual null below
    else:
        L_obs_kont = nan_r.copy()

    # ------------------------------------------------------------------
    # Simulation loops
    # ------------------------------------------------------------------
    sims_orig = []
    sims_kont = []

    for _ in range(args.n_sim):
        # L_original null: global permutation
        perm_global = rng.permutation(labels)
        mask_ct_g   = perm_global == ct
        ci_g        = coordinates[mask_ct_g]
        wi_g        = global_weights[mask_ct_g]
        sims_orig.append(cross_L_original(ci_g, ci_g, RADII, wi_g, global_area))

        # L_kontextual null: pool-restricted permutation
        # Degenerate when pool contains only ct (all draws identical) — stored
        # but downstream stats will show z = NaN / p = NaN via zero variance.
        if pool_ct is not None and n_src >= args.min_cells:
            perm_l_ct   = rng.permutation(perm_labels_ct)
            mask_i_p    = perm_l_ct == ct
            ci_p        = perm_coords_ct[mask_i_p]
            wi_p        = pool_gw_ct[mask_i_p]
            n_par_p     = n_par_at_pool_ct[mask_i_p]
            nj_p        = int(np.sum(mask_i_p))
            sims_kont.append(cross_L_kontextual(
                ci_p, ci_p,
                n_par_p, n_par_p,
                n_pool_ct, nj_p, wi_p, RADII))

    sims_orig  = np.array(sims_orig)                        # (n_sim, N_R)
    stats_orig = _integral_stats(L_obs_orig, sims_orig, RADII)

    if sims_kont:
        sims_kont_arr  = np.array(sims_kont)
        stats_kont     = _integral_stats(L_obs_kont, sims_kont_arr, RADII)
    else:
        sims_kont_arr  = np.empty((0, N_R))
        stats_kont     = None

    results[(ct, ct)] = {
        "type_i":          ct,
        "type_j":          ct,
        "parent_name":     parent_name_ct,
        "perm_pool_types": sorted(perm_types_ct),
        "r":               RADII.copy(),
        # ---- original (global null) ----
        "L_original":              L_obs_orig,
        "L_original_sim_mean":     stats_orig['sim_mean'],
        "L_original_sim_std":      stats_orig['sim_std'],
        "L_original_simulations":  sims_orig,
        "pvalues_original":        stats_orig['pvalues'],
        "integral_original":       stats_orig['integral_signed'],
        "integral_original_abs":   stats_orig['integral_abs'],
        "z_original":              stats_orig['z_integral'],
        "p_original":              stats_orig['p_integral'],
        # ---- kontextual (pool-restricted null; NaN if pool = self-only) ----
        "L_kontextual":                L_obs_kont,
        "L_kontextual_sim_mean":       stats_kont['sim_mean']        if stats_kont else nan_r.copy(),
        "L_kontextual_sim_std":        stats_kont['sim_std']         if stats_kont else nan_r.copy(),
        "L_kontextual_simulations":    sims_kont_arr,
        "pvalues_kontextual":          stats_kont['pvalues']         if stats_kont else nan_r.copy(),
        "integral_kontextual":         stats_kont['integral_signed'] if stats_kont else np.nan,
        "integral_kontextual_abs":     stats_kont['integral_abs']    if stats_kont else np.nan,
        "z_kontextual":                stats_kont['z_integral']      if stats_kont else np.nan,
        "p_kontextual":                stats_kont['p_integral']      if stats_kont else np.nan,
        # ---- counts / diagnostics ----
        "n_source_cells":      n_ct,
        "n_target_cells":      n_ct,
        "n_valid_simulations": len(sims_orig),
        "n_failed_simulations": 0,
        "reason":              None,
    }
    print(f"  [{ct}] done  (n={n_ct}, pool types={sorted(perm_types_ct)})")

print(f"\nDiagonal done: "
      f"{sum(1 for (ti,tj),v in results.items() if ti==tj and v['reason'] is None)} "
      f"types computed.")

#==============================================================================
# 5  Build summary table and save results
#==============================================================================

# --- Summary TSV -------------------------------------------------------------
summary_rows = []
for (ti, tj), res in results.items():
    def _minpval(pv):
        return float(np.nanmin(pv)) if not np.all(np.isnan(pv)) else np.nan
    def _minr(pv):
        idx = int(np.nanargmin(pv)) if not np.all(np.isnan(pv)) else None
        return float(RADII[idx]) if idx is not None else np.nan

    summary_rows.append({
        "from":                         res["type_i"],
        "to":                           res["type_j"],
        "parent_name":                  res["parent_name"],
        "n_source_cells":               res["n_source_cells"],
        "n_target_cells":               res["n_target_cells"],
        # original
        "integral_original":            res["integral_original"],
        "integral_original_abs":        res["integral_original_abs"],
        "z_original":                   res["z_original"],
        "p_original":                   res["p_original"],
        "min_pval_original":            _minpval(res["pvalues_original"]),
        "r_min_pval_original":          _minr(res["pvalues_original"]),
        # kontextual
        "integral_kontextual":          res["integral_kontextual"],
        "integral_kontextual_abs":      res["integral_kontextual_abs"],
        "z_kontextual":                 res["z_kontextual"],
        "p_kontextual":                 res["p_kontextual"],
        "min_pval_kontextual":          _minpval(res["pvalues_kontextual"]),
        "r_min_pval_kontextual":        _minr(res["pvalues_kontextual"]),
        # diagnostics
        "n_valid_simulations":          res["n_valid_simulations"],
        "n_failed_simulations":         res["n_failed_simulations"],
        "reason":                       res["reason"],
    })

summary_df = pd.DataFrame(summary_rows)

# --- Save pickle -------------------------------------------------------------
pkl_path = os.path.join(args.output_dir_results, "kontextual_ripleys_L.pkl")
with open(pkl_path, "wb") as f:
    pickle.dump(results, f)
print(f"Full results  → {pkl_path}")

# --- Save summary TSV --------------------------------------------------------
tsv_path = os.path.join(args.output_dir_results, "kontextual_ripleys_summary.tsv")
summary_df.to_csv(tsv_path, sep='\t', index=False)
print(f"Summary table → {tsv_path}")

print("\nDone.")
